### ISSUE TITLE
Usage in README is incorrect

### ISSUE THREAD

**Issue by kai2nenobu** [skanehira/remonade#15]
I downloaded `remonade` 0.0.1 and followed  a usage in [`README.md`](https://github.com/skanehira/remonade/blob/0a4d084e027efdfb0c12e2944a5503737d06bd93/README.md#usage), but errors occured.

```console
$ remonade init
Error: unknown command "init" for "remonade"
Run 'remonade --help' for usage.
unknown command "init" for "remonade"
$ remonade edit
Error: unknown command "edit" for "remonade"
Run 'remonade --help' for usage.
unknown command "edit" for "remonade"
```

Maybe, `remonade config init` and `remonade config edit` are correct?

**Comment by skanehira** [comment]
@kai2nenobu Yes, README was incorrect, I fixed README.
Thank you for report
